Update patch set 4
Patch Set 4: Verified-1

Error is now

system/bt/btif/src/btif_vendor.c:109:1: error: missing field 'cleanup' initializer [-Werror,-Wmissing-field-initializers]

No idea how to fix this.  Same references of cleanup as in nougat-mr1 so not sure how it could be missing

Patch-set: 4
Reviewer: Gerrit User 1000012 <1000012@3162e3d8-d894-470e-abd9-724f7b0effad>
Label: Verified=-1